// wiki/specs/_design-refs/B60/ProgressBar.jsx
// ProgressBar — linear progress with over-budget state.
// pct accepts 0–120. Fill is var(--<tone>) up to 100; switches to --danger when
// >100, with a 3px --danger notch pinned to the right edge to signal overflow.

function ProgressBar({ pct = 0, tone = "ok", label, showPct = true }) {
  const over = pct > 100;
  const clamped = Math.max(0, Math.min(100, pct));
  const fill = over ? "var(--danger)" : `var(--${tone})`;
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 4, width: "100%" }}>
      {(label || showPct) && (
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            fontFamily: "var(--mono)",
            fontSize: 10,
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "var(--ink-faint)",
          }}
        >
          <span>{label}</span>
          {showPct && <span style={{ color: over ? "var(--danger)" : `var(--${tone})` }}>{Math.round(pct)}%</span>}
        </div>
      )}
      <div style={{ position: "relative", height: 5, background: "var(--bg-sunken)", border: "1px solid var(--rule)" }}>
        <div style={{ height: "100%", width: `${clamped}%`, background: fill, transition: "width 0.3s" }} />
        {over && <div style={{ position: "absolute", top: -1, bottom: -1, right: 0, width: 3, background: "var(--danger)" }} />}
      </div>
    </div>
  );
}

Object.assign(window, { ProgressBar });

// src/lib/components/patterns/ProgressBar.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'

  type ProgressColor = 'ok' | 'amber' | 'danger'

  interface Props extends HTMLAttributes<HTMLDivElement> {
    value: number
    label?: string
    color?: ProgressColor
    [key: string]: unknown
  }

  let {
    value,
    label,
    color = 'ok',
    ...rest
  }: Props = $props()

  const clampedValue = $derived(Math.min(100, Math.max(0, value)))
</script>

<div class="progress" {...rest}>
  {#if label}
    <div class="progress-header" aria-hidden="true">
      <span>{label}</span>
      <span class="progress-pct progress-pct--{color}">{clampedValue}%</span>
    </div>
  {/if}
  <div
    class="progress-track"
    role="progressbar"
    aria-valuenow={clampedValue}
    aria-valuemin={0}
    aria-valuemax={100}
    aria-label={label ?? 'Progress'}
  >
    <div
      class="progress-fill progress-fill--{color}"
      style="width: {clampedValue}%"
    ></div>
  </div>
</div>

<style>
  .progress {
    display: flex;
    flex-direction: column;
    gap: 4px;
    width: 100%;
  }

  .progress-header {
    display: flex;
    justify-content: space-between;
    font-family: var(--mono);
    font-size: var(--t-micro);
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--ink-faint);
  }

  .progress-pct--ok     { color: var(--ok); }
  .progress-pct--amber  { color: var(--amber); }
  .progress-pct--danger { color: var(--danger); }

  .progress-track {
    height: 5px;
    background: var(--bg-sunken);
    border: 1px solid var(--rule);
  }

  .progress-fill {
    height: 100%;
    background: var(--ok);
    transition: width 0.3s;
  }

  .progress-fill--amber  { background: var(--amber); }
  .progress-fill--danger { background: var(--danger); }
</style>
